// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type ArchiveDocumentDataSlicesSlice = never

/**
 * Content for Archive documents
 */
interface ArchiveDocumentData {
  /**
   * year field in *Archive*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  year: prismic.NumberField

  /**
   * Title field in *Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Client field in *Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.client
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  client: prismic.KeyTextField

  /**
   * Role field in *Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField

  /**
   * Image field in *Archive*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Description field in *Archive*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * External Url field in *Archive*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.external_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  external_url: prismic.LinkField

  /**
   * Slice Zone field in *Archive*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArchiveDocumentDataSlicesSlice> /**
   * Meta Description field in *Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: archive.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Archive*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: archive.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Archive document from Prismic
 *
 * - **API ID**: `archive`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArchiveDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ArchiveDocumentData>, 'archive', Lang>

type ProjectDocumentDataSlicesSlice = VideoShowcaseSlice | MediaShowcaseSlice

type ProjectDocumentDataSlices1Slice = never

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Project title
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Client field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Self-initiated
   * - **API ID Path**: project.client
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  client: prismic.KeyTextField

  /**
   * Year field in *Project*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 2024
   * - **API ID Path**: project.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  year: prismic.NumberField

  /**
   * Role field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Typeface design, Web dev
   * - **API ID Path**: project.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField

  /**
   * External Url field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://anassageneral.gr
   * - **API ID Path**: project.external_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  external_url: prismic.LinkField

  /**
   * Heading field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Air Company, a carbon technology company that is creating products from CO2 to extend life on Earth.
   * - **API ID Path**: project.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField

  /**
   * Cover Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices1[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<ProjectDocumentDataSlices1Slice>
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, 'project', Lang>

export type AllDocumentTypes = ArchiveDocument | ProjectDocument

/**
 * Primary content in *ImageShowcase → Primary*
 */
export interface MediaShowcaseSliceDefaultPrimary {
  /**
   * Image field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_showcase.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * ratio field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 16/9
   * - **API ID Path**: media_showcase.primary.ratio
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ratio: prismic.NumberField

  /**
   * distance field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 125
   * - **API ID Path**: media_showcase.primary.distance
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  distance: prismic.NumberField

  /**
   * delay field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 0.575
   * - **API ID Path**: media_showcase.primary.delay
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  delay: prismic.NumberField
}

/**
 * Full Width variation for ImageShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaShowcaseSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MediaShowcaseSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *ImageShowcase → Primary*
 */
export interface MediaShowcaseSliceHalfleftPrimary {
  /**
   * Image field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_showcase.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * ratio field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 16/9
   * - **API ID Path**: media_showcase.primary.ratio
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ratio: prismic.NumberField

  /**
   * distance field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 125
   * - **API ID Path**: media_showcase.primary.distance
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  distance: prismic.NumberField

  /**
   * delay field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 0.575
   * - **API ID Path**: media_showcase.primary.delay
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  delay: prismic.NumberField
}

/**
 * Half Width - Left variation for ImageShowcase Slice
 *
 * - **API ID**: `halfleft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaShowcaseSliceHalfleft = prismic.SharedSliceVariation<
  'halfleft',
  Simplify<MediaShowcaseSliceHalfleftPrimary>,
  never
>

/**
 * Primary content in *ImageShowcase → Primary*
 */
export interface MediaShowcaseSliceHalfrightPrimary {
  /**
   * Image field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_showcase.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * ratio field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 16/9
   * - **API ID Path**: media_showcase.primary.ratio
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ratio: prismic.NumberField

  /**
   * distance field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 125
   * - **API ID Path**: media_showcase.primary.distance
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  distance: prismic.NumberField

  /**
   * delay field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 0.575
   * - **API ID Path**: media_showcase.primary.delay
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  delay: prismic.NumberField
}

/**
 * Half Width - Right variation for ImageShowcase Slice
 *
 * - **API ID**: `halfright`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaShowcaseSliceHalfright = prismic.SharedSliceVariation<
  'halfright',
  Simplify<MediaShowcaseSliceHalfrightPrimary>,
  never
>

/**
 * Primary content in *ImageShowcase → Primary*
 */
export interface MediaShowcaseSliceHalfmidPrimary {
  /**
   * Image field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_showcase.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * ratio field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 16/9
   * - **API ID Path**: media_showcase.primary.ratio
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ratio: prismic.NumberField

  /**
   * distance field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 125
   * - **API ID Path**: media_showcase.primary.distance
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  distance: prismic.NumberField

  /**
   * delay field in *ImageShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 0.575
   * - **API ID Path**: media_showcase.primary.delay
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  delay: prismic.NumberField
}

/**
 * Half Width - Mid variation for ImageShowcase Slice
 *
 * - **API ID**: `halfmid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaShowcaseSliceHalfmid = prismic.SharedSliceVariation<
  'halfmid',
  Simplify<MediaShowcaseSliceHalfmidPrimary>,
  never
>

/**
 * Slice variation for *ImageShowcase*
 */
type MediaShowcaseSliceVariation =
  | MediaShowcaseSliceDefault
  | MediaShowcaseSliceHalfleft
  | MediaShowcaseSliceHalfright
  | MediaShowcaseSliceHalfmid

/**
 * ImageShowcase Shared Slice
 *
 * - **API ID**: `media_showcase`
 * - **Description**: MediaShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaShowcaseSlice = prismic.SharedSlice<
  'media_showcase',
  MediaShowcaseSliceVariation
>

/**
 * Primary content in *VideoShowcase → Primary*
 */
export interface VideoShowcaseSliceDefaultPrimary {
  /**
   * Ratio field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.ratio
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ratio: prismic.NumberField

  /**
   * Distance field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.distance
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  distance: prismic.NumberField

  /**
   * Delay field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.delay
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  delay: prismic.NumberField

  /**
   * Video URL field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: dqoxwlhrv/video/upload/f_auto:video,w_1920,q_auto:best/xx36shsmwnxo8doholak
   * - **API ID Path**: video_showcase.primary.video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField
}

/**
 * Full Width variation for VideoShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoShowcaseSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<VideoShowcaseSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *VideoShowcase → Primary*
 */
export interface VideoShowcaseSliceHalfleftPrimary {
  /**
   * Ratio field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.ratio
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ratio: prismic.NumberField

  /**
   * Distance field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.distance
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  distance: prismic.NumberField

  /**
   * Delay field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.delay
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  delay: prismic.NumberField

  /**
   * Video URL field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: dqoxwlhrv/video/upload/f_auto:video,w_1920,q_auto:best/xx36shsmwnxo8doholak
   * - **API ID Path**: video_showcase.primary.video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField
}

/**
 * Half Width - Left variation for VideoShowcase Slice
 *
 * - **API ID**: `halfleft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoShowcaseSliceHalfleft = prismic.SharedSliceVariation<
  'halfleft',
  Simplify<VideoShowcaseSliceHalfleftPrimary>,
  never
>

/**
 * Primary content in *VideoShowcase → Primary*
 */
export interface VideoShowcaseSliceHalfrightPrimary {
  /**
   * Ratio field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.ratio
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ratio: prismic.NumberField

  /**
   * Distance field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.distance
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  distance: prismic.NumberField

  /**
   * Delay field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.delay
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  delay: prismic.NumberField

  /**
   * Video URL field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: dqoxwlhrv/video/upload/f_auto:video,w_1920,q_auto:best/xx36shsmwnxo8doholak
   * - **API ID Path**: video_showcase.primary.video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField
}

/**
 * Half Width - Right variation for VideoShowcase Slice
 *
 * - **API ID**: `halfright`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoShowcaseSliceHalfright = prismic.SharedSliceVariation<
  'halfright',
  Simplify<VideoShowcaseSliceHalfrightPrimary>,
  never
>

/**
 * Primary content in *VideoShowcase → Primary*
 */
export interface VideoShowcaseSliceHalfmidPrimary {
  /**
   * Ratio field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.ratio
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ratio: prismic.NumberField

  /**
   * Distance field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.distance
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  distance: prismic.NumberField

  /**
   * Delay field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.primary.delay
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  delay: prismic.NumberField

  /**
   * Video URL field in *VideoShowcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: dqoxwlhrv/video/upload/f_auto:video,w_1920,q_auto:best/xx36shsmwnxo8doholak
   * - **API ID Path**: video_showcase.primary.video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField
}

/**
 * Half Width - Mid variation for VideoShowcase Slice
 *
 * - **API ID**: `halfmid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoShowcaseSliceHalfmid = prismic.SharedSliceVariation<
  'halfmid',
  Simplify<VideoShowcaseSliceHalfmidPrimary>,
  never
>

/**
 * Slice variation for *VideoShowcase*
 */
type VideoShowcaseSliceVariation =
  | VideoShowcaseSliceDefault
  | VideoShowcaseSliceHalfleft
  | VideoShowcaseSliceHalfright
  | VideoShowcaseSliceHalfmid

/**
 * VideoShowcase Shared Slice
 *
 * - **API ID**: `video_showcase`
 * - **Description**: VideoShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoShowcaseSlice = prismic.SharedSlice<
  'video_showcase',
  VideoShowcaseSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      ArchiveDocument,
      ArchiveDocumentData,
      ArchiveDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ProjectDocumentDataSlices1Slice,
      AllDocumentTypes,
      MediaShowcaseSlice,
      MediaShowcaseSliceDefaultPrimary,
      MediaShowcaseSliceHalfleftPrimary,
      MediaShowcaseSliceHalfrightPrimary,
      MediaShowcaseSliceHalfmidPrimary,
      MediaShowcaseSliceVariation,
      MediaShowcaseSliceDefault,
      MediaShowcaseSliceHalfleft,
      MediaShowcaseSliceHalfright,
      MediaShowcaseSliceHalfmid,
      VideoShowcaseSlice,
      VideoShowcaseSliceDefaultPrimary,
      VideoShowcaseSliceHalfleftPrimary,
      VideoShowcaseSliceHalfrightPrimary,
      VideoShowcaseSliceHalfmidPrimary,
      VideoShowcaseSliceVariation,
      VideoShowcaseSliceDefault,
      VideoShowcaseSliceHalfleft,
      VideoShowcaseSliceHalfright,
      VideoShowcaseSliceHalfmid,
    }
  }
}
