'use client'

import Scene from '@/components/3d/scene'
import BezierCurve from '@/components/new/bezier-curve'
import Footer from '@/components/new/footer'
import IntroStripe from '@/components/new/intro-stripe'
import Reveal from '@/components/new/reveal'
import Table from '@/components/new/table'
import TransitionPane from '@/components/transition/pane'
import AspectRatioImage from '@/components/ui/aspect-ratio-image'
import Magnetic from '@/components/ui/magnetic'
import Marquee from '@/components/ui/marquee'
import Page from '@/components/ui/page'
import Section from '@/components/ui/section'
import TextRevealByChar from '@/components/ui/text-reveal-char'
import VelocityMarquee from '@/components/ui/velocity-marquee'
import { useScrollToTop } from '@/lib/hooks'
import { useInView } from 'framer-motion'
import Head from 'next/head'
import React, {
  DetailedHTMLProps,
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
  cloneElement,
} from 'react'
import { useRef } from 'react'

export default function About() {
  const paneRef = useRef<HTMLDivElement>(null)
  const textRef = useRef<HTMLParagraphElement>(null)
  // const wrapperRef = useRef<HTMLDivElement>(null)
  // const isInView = useInView(wrapperRef, { once: true })

  // if (isInView) {
  //   console.log('duplicate home page')
  // }

  useScrollToTop()

  const setBodyBg = (color: string) => {
    document.body.style.backgroundColor = color
  }

  return (
    <React.Fragment>
      <Head>
        <title>SVG App</title>
        <meta name={'description'} content={'Generated by create next app'} />
        <meta
          name={'viewport'}
          content={'width=device-width, initial-scale=1'}
        />
        <link rel={'icon'} href={'/favicon.ico'} />
      </Head>

      <TransitionPane ref={paneRef}>
        <Page>
          <VelocityMarquee className={'cursor-default'} direction={1}>
            <Marquee className={'pt-0'}>
              <TextRevealByChar
                as={'h1'}
                lineHeight={'1.195em'}
                delay={0}
                enterY={'22.125%'}
                id={'hero-entry'}
                className={'ml-2 pl-6'}
                typeClass={'typography-display'}
                text={'GeorgeCht©2024'}
              />
            </Marquee>
          </VelocityMarquee>
          <IntroStripe />
          <Section withPadding withGap className={'sm:pt-1.5'}>
            <AspectRatioImage
              src={'/12.png'}
              ratio={16 / 9}
              responsiveRatio={1 / 1.1}
              distance={125}
              delay={0.575}
              className={'mb-2'}
            />
          </Section>
          <Section withPadding withGap className={'sm:pt-1.5'}>
            <AspectRatioImage
              src={'/13.png'}
              ratio={16 / 9}
              responsiveRatio={1 / 1.1}
              distance={125}
              className={'mb-2'}
            />
          </Section>
          <Section
            withPadding
            withGap
            className={'flex-col md:flex-row sm:pt-1.5'}
          >
            <div className={'md:w-1/2 w-full'} />
            <div className={'md:w-1/2 w-full'}>
              <AspectRatioImage
                src={'/12.png'}
                ratio={1 / 1.1}
                responsiveRatio={1 / 1.1}
                distance={125}
                className={'mb-2'}
              />
            </div>
          </Section>
          <Section
            withPadding
            withGap
            className={'flex-col md:flex-row sm:pt-1.5'}
          >
            <div className={'md:w-1/2 w-full'}>
              <AspectRatioImage
                src={'/12.png'}
                ratio={1 / 1.1}
                responsiveRatio={1 / 1.1}
                distance={125}
                className={'mb-2'}
              />
            </div>
            <div className={'md:w-1/2 w-full'} />
          </Section>
          <Section
            withPadding
            withGap
            className={'flex-col md:flex-row sm:pt-1.5'}
          >
            <div className={'w-1/6 hidden lg:flex'} />
            <div className={'md:w-1/2 w-full'}>
              <AspectRatioImage
                src={'/12.png'}
                ratio={1 / 1.1}
                responsiveRatio={1 / 1.1}
                distance={125}
                className={'mb-2'}
              />
            </div>
            <div className={'w-4/12 hidden lg:flex'} />
          </Section>

          <Section
            withPadding
            withGap
            className={'sm:flex-row pt-16 sm:pt-48 gap-2.5 w-full'}
          >
            <div className={'w-1/6 hidden lg:flex'} />
            <div className={'w-full sm:w-1/2 lg:w-1/3'}>
              <Reveal opacity childrenRef={textRef} duration={1}>
                <p className={'typography-base max-w-[620px]'} ref={textRef}>
                  Designed to save time while maintaining a strong visual
                  presence on various social media channels, these templates
                  feature a perfect blend of classic and contemporary styles.
                </p>
              </Reveal>
            </div>
            <div className={'w-full sm:w-1/2 lg:w-1/3'}>
              <Reveal opacity childrenRef={textRef} duration={1} delay={0.275}>
                <p className={'typography-base max-w-[620px]'} ref={textRef}>
                  Designed to save time while maintaining a strong visual
                  presence on various social media channels, these templates
                  feature a perfect blend of classic and contemporary styles.
                </p>
              </Reveal>
            </div>
            <div className={'w-1/6 hidden lg:flex'} />
          </Section>
          <Table.Preview />
          <Footer />
        </Page>
      </TransitionPane>
    </React.Fragment>
  )
}
