'use client'

import Footer from '@/components/new/footer'
import Reveal from '@/components/new/reveal'
import Table from '@/components/new/table'
import TransitionPane from '@/components/transition/pane'
import AspectRatioImage from '@/components/ui/aspect-ratio-image'
import Page from '@/components/ui/page'
import Section from '@/components/ui/section'
import Head from 'next/head'
import React, { useRef } from 'react'
import { useScrollToTop } from '@/lib/hooks'
import VelocityMarquee from '@/components/ui/velocity-marquee'
import Marquee from '@/components/ui/marquee'
import TextRevealByChar from '@/components/ui/text-reveal-char'
import Link, { LinkProps } from 'next/link'
import TextReveal from '@/components/ui/text-reveal'
import { cn } from '@/lib/utils'

const ProjectEntry = ({
  index,
  image,
  title,
  year,
  href,
  className,
  ...props
}: LinkProps & {
  index: number
  image: string
  title: string
  year: string | number
  className?: string
}) => {
  const headerRef = useRef<HTMLParagraphElement>(null)
  return (
    <Link
      href={href}
      scroll={false}
      className={cn('flex flex-col w-full lg:w-1/3', className)}
      {...props}
    >
      <TextReveal
        as={'p'}
        lineHeight={'0.85em'}
        enterY={'10%'}
        className={'mb-1.5'}
        typeClass={'typography-caps-sm'}
        text={`00${index}`}
        delay={index * 0.125}
      />
      <AspectRatioImage
        src={image}
        ratio={9 / 16}
        responsiveBreakpoint={1024}
        responsiveRatio={1 / 1.1}
        distance={125}
        className={'mb-2'}
        delay={index * 0.125}
      />
      <Reveal opacity childrenRef={headerRef} duration={1}>
        <h2 className={'typography-lg w-full md:max-w-[49vw]'} ref={headerRef}>
          {title}
        </h2>
      </Reveal>
      <TextReveal
        as={'p'}
        lineHeight={'1em'}
        enterY={'10%'}
        className={'mb-0 sm:-mb-3.5'}
        typeClass={'typography-sm'}
        text={String(year)}
      />
    </Link>
  )
}

export default function About() {
  const paneRef = useRef<HTMLDivElement>(null)
  const buttonRef = useRef<HTMLDivElement>(null)
  const textRef = useRef<HTMLParagraphElement>(null)
  const headerRef = useRef<HTMLParagraphElement>(null)
  useScrollToTop()

  return (
    <React.Fragment>
      <Head>
        <title>SVG App</title>
        <meta name={'description'} content={'Generated by create next app'} />
        <meta
          name={'viewport'}
          content={'width=device-width, initial-scale=1'}
        />
        <link rel={'icon'} href={'/favicon.ico'} />
      </Head>

      <TransitionPane ref={paneRef}>
        <Page>
          <VelocityMarquee className={'cursor-default'} direction={1}>
            <Marquee className={'pt-0'}>
              <TextRevealByChar
                as={'h1'}
                lineHeight={'1.195em'}
                delay={0}
                enterY={'22.125%'}
                id={'hero-entry'}
                className={'ml-2 pl-6'}
                typeClass={'typography-display'}
                text={'Projects↙'}
              />
            </Marquee>
          </VelocityMarquee>
          <Section
            withPadding
            className={'pt-6 gap-6 sm:gap-0 pb-4 lg:flex-row'}
          >
            <ProjectEntry
              title={'Anassa General'}
              year={2022}
              image={'/12.png'}
              index={1}
              href={'/project'}
            />
            <ProjectEntry
              title={'Anassa General'}
              year={2022}
              image={'/12.png'}
              index={2}
              href={'/project'}
            />
            <ProjectEntry
              title={'Anassa General'}
              year={2022}
              image={'/12.png'}
              index={3}
              href={'/project'}
            />
          </Section>
          <Section
            withPadding
            className={'pt-6 gap-6 sm:gap-0 pb-24 lg:flex-row'}
          >
            <ProjectEntry
              title={'Anassa General'}
              year={2022}
              image={'/12.png'}
              index={4}
              href={'/project'}
            />
            <ProjectEntry
              title={'Anassa General'}
              year={2022}
              image={'/12.png'}
              index={5}
              href={'/project'}
            />
            <ProjectEntry
              title={'Anassa General'}
              year={2022}
              image={'/12.png'}
              index={6}
              href={'/project'}
            />
          </Section>
          <VelocityMarquee className={'cursor-default'} direction={1}>
            <Marquee className={'pt-0'}>
              <TextRevealByChar
                as={'h1'}
                lineHeight={'1.195em'}
                delay={0}
                enterY={'22.125%'}
                id={'hero-entry'}
                className={'ml-2 pl-6'}
                typeClass={'typography-display'}
                text={'Archive↙'}
              />
            </Marquee>
          </VelocityMarquee>
          <Table.Preview />
          <Footer />
        </Page>
      </TransitionPane>
    </React.Fragment>
  )
}
