// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  media_showcase: dynamic(() => import('./ImageShowcase')),
  video_showcase: dynamic(() => import('./VideoShowcase')),
}
